/** Canonical education levels and courses (kept in sync with App/lib/profile/education_options.dart). */

export const EDUCATION_LEVELS = [
  '10th / SSC',
  '12th / HSC',
  'ITI',
  'Diploma',
  "Bachelor's degree",
  "Master's degree",
  'PhD / Doctorate',
  'Post Graduate Diploma',
  'Certificate / Short course',
  'Other',
];

export const FIELD_OF_STUDY_BY_LEVEL = {
  '10th / SSC': ['General', 'Science', 'Commerce', 'Arts', 'Vocational', 'Other'],
  '12th / HSC': [
    'Science (PCM)',
    'Science (PCB)',
    'Commerce',
    'Arts / Humanities',
    'Vocational',
    'Other',
  ],
  ITI: [
    'Electrician',
    'Fitter',
    'Welder',
    'Mechanic (Motor Vehicle)',
    'COPA (Computer Operator)',
    'Plumber',
    'Wireman',
    'Other',
  ],
  Diploma: [
    'Engineering (Polytechnic)',
    'Pharmacy (D.Pharm)',
    'Nursing',
    'Hotel Management',
    'Architecture Assistant',
    'Other',
  ],
  "Bachelor's degree": [
    'B.Tech / BE',
    'B.Com',
    'B.A',
    'B.Sc',
    'BBA',
    'BCA',
    'MBBS',
    'B.Pharm',
    'LLB',
    'B.Arch',
    'B.Ed',
    'Other',
  ],
  "Master's degree": [
    'M.Tech',
    'MBA',
    'M.Com',
    'M.A',
    'M.Sc',
    'MCA',
    'MSW',
    'M.Pharm',
    'LLM',
    'Other',
  ],
  'PhD / Doctorate': [
    'Science',
    'Engineering',
    'Management',
    'Humanities',
    'Medicine',
    'Other',
  ],
  'Post Graduate Diploma': [
    'PGDM',
    'PG Diploma (Technical)',
    'PG Diploma (Management)',
    'Other',
  ],
  'Certificate / Short course': [
    'Professional Certification',
    'Skill Development',
    'Online Course',
    'Other',
  ],
  Other: ['Other'],
};
